apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello
    app.kubernetes.io/part-of: build-nudge-example
  name: node-express-hello
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-express-hello
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: node-express-hello
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/arewm-tenant/build-nudge-example/node-express-hello@sha256:418ffc095e8b6fd0cdc1475b02e6618467707ba310967ea257a7b319948d37f4
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
