apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: node-express-hello
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node-express-hello
    app.kubernetes.io/part-of: build-nudge-example
  name: node-express-hello
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: node-express-hello
status:
  loadBalancer: {}
